# Form implementation generated from reading ui file 'C:\Users\BIT\Desktop\education\7sem\SUBD\PythonProject\SecondWindow.ui'
#
# Created by: PyQt6 UI code generator 6.3.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(894, 814)
        self.pushButton6 = QtWidgets.QPushButton(Dialog)
        self.pushButton6.setGeometry(QtCore.QRect(320, 450, 181, 71))
        self.pushButton6.setObjectName("pushButton6")
        self.pushButton4 = QtWidgets.QPushButton(Dialog)
        self.pushButton4.setGeometry(QtCore.QRect(30, 40, 831, 101))
        self.pushButton4.setObjectName("pushButton4")
        self.pushButton8 = QtWidgets.QPushButton(Dialog)
        self.pushButton8.setGeometry(QtCore.QRect(30, 180, 831, 111))
        self.pushButton8.setObjectName("pushButton8")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.pushButton6.setText(_translate("Dialog", "Вернуться назад "))
        self.pushButton4.setText(_translate("Dialog", "Просмотр информации о конкурсах на  соискание  грантов  "))
        self.pushButton8.setText(_translate("Dialog", "Просмотр информации о НИР выполняемых по грантам"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec())
